.TH SUTURE-SHOW "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-show \- Show detailed information about a commit
.SH SYNOPSIS
.B suture show [\\fIoptions\\fR] \\fIcommit\\fR
.SH DESCRIPTION
Show detailed information about a commit.
.SH OPTIONS
.TP
.BR \\\-\\\-stat
Show file change statistics
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH EXAMPLES
.nf
suture show HEAD           # Show HEAD commit
suture show abc123         # Show specific commit
suture show \\\-\\\-stat HEAD    # Show with file change statistics
.fi
.SH SEE ALSO
.BR suture (1)
