.TH SUTURE-DOCTOR "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-doctor \- Check repository health and configuration
.SH SYNOPSIS
.B suture doctor [\\fIoptions\\fR]
.SH DESCRIPTION
Check repository health and configuration.
.SH OPTIONS
.TP
.BR \\\-\\\-fix
Automatically fix detected issues
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH SEE ALSO
.BR suture (1)
