.TH SUTURE-FETCH "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-fetch \- Fetch patches from a remote Hub without merging
.SH SYNOPSIS
.B suture fetch [\\fIoptions\\fR] [\\fIremote\\fR]
.SH DESCRIPTION
Fetch patches from a remote Hub without merging.
.SH OPTIONS
.TP
.BR \\\-\\\-depth \\fI<n>\\fR
Limit fetch to the last N commits
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH EXAMPLES
.nf
suture fetch               # Fetch from origin
suture fetch \\\-\\\-depth 5     # Shallow fetch last 5 commits
.fi
.SH SEE ALSO
.BR suture (1)
