.TH SUTURE-TUI "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-tui \- Launch terminal UI
.SH SYNOPSIS
.B suture tui [\\fIoptions\\fR]
.SH DESCRIPTION
Launch terminal UI.
.SH OPTIONS
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH SEE ALSO
.BR suture (1)
