.TH SUTURE-MV "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-mv \- Move or rename a tracked file
.SH SYNOPSIS
.B suture mv [\\fIoptions\\fR] \\fIsource\\fR \\fIdestination\\fR
.SH DESCRIPTION
Move or rename a tracked file.
.SH OPTIONS
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH EXAMPLES
.nf
suture mv old.txt new.txt  # Rename a file
suture mv file dir/        # Move file into directory
.fi
.SH SEE ALSO
.BR suture (1)
