.TH SUTURE-SHORTLOG "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-shortlog \- Show compact commit summary grouped by author
.SH SYNOPSIS
.B suture shortlog [\\fIoptions\\fR] [\\fIbranch\\fR]
.SH DESCRIPTION
Show compact commit summary grouped by author.
.SH OPTIONS
.TP
.BR \\\-n, \\\-\\\-number \\fI<n>\\fR
Number of commits to show (default: all)
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH SEE ALSO
.BR suture (1)
