.TH SUTURE-REFLOG "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-reflog \- Show the reference log (HEAD movements)
.SH SYNOPSIS
.B suture reflog [\\fIoptions\\fR]
.SH DESCRIPTION
Show the reference log (HEAD movements).
.SH OPTIONS
.TP
.BR \\\-\\\-show
Show full patch details for each reflog entry
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH SEE ALSO
.BR suture (1)
