.TH SUTURE-STATUS "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-status \- Show repository status
.SH SYNOPSIS
.B suture status [\\fIoptions\\fR]
.SH DESCRIPTION
Show repository status.
.SH OPTIONS
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH EXAMPLES
.nf
suture status              # Show working tree status
.fi
.SH SEE ALSO
.BR suture (1)
