.TH SUTURE-CLASSIFICATION "1" "April 2026" "Suture v5.0.0" "User Commands"
.SH NAME
suture\-classification \- Bulk classification marking scanning and compliance reporting
.SH SYNOPSIS
.B suture classification [\\fIoptions\\fR] \\fIcommand\\fR
.SH DESCRIPTION
Bulk classification marking scanning and compliance reporting.
.SH SUBCOMMANDS
.TP
.B scan
Scan all commits for classification marking changes
.TP
.B report
Generate classification compliance report
.SH OPTIONS
.TP
.BR \\\-C \\fI<REPO_PATH>\\fR
Run as if suture was started in <path>
.TP
.BR \\\-h, \\\-\\\-help
Print help
.SH SEE ALSO
.BR suture (1)
