[package]
name = "suture-driver-ui"
version = "5.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true
description.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
categories.workspace = true

[dependencies]
suture-driver = { path = "../suture-driver", version = "5.0.0" }
suture-core = { path = "../suture-core", version = "5.0.0" }
roxmltree = { version = "0.21", features = ["positions"] }

[dev-dependencies]
proptest = "1"
